config/routes.rb
Fourk::Application.routes.draw do
  resources :rates

  resources :prices

  resources :categories

  get '/uso', to: 'welcome#usage'
  get '/privacidade', to: 'welcome#privacy'
  get '/', to: 'welcome#index'
  root :to => 'welcome#index'

  get '/establishments/:id/foods', to: 'establishments#foods'

  resources 'establishments', only: [:index, :new, :create, :show, :edit, :update] do
    member do
      get :foods
      post :food_add
      post :food_remove

      get :categories
      post :category_add
      post :category_remove
    end
  end
  
  resources :foods, only: [:index, :new, :create, :show, :edit, :update] do
    member do
      get :categories
      post :category_add
      post :category_remove
    end
  end

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/food.rb
class Food < ActiveRecord::Base
  validates :name, presence: true

  has_and_belongs_to_many :establishments
  has_and_belongs_to_many :categories
  has_many :prices
  has_many :rates, as: :rateable

  def enrolled_in_category?(category)
    self.categories.include?(category)
  end

  def unenrolled_categories
    Category.all - self.categories
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new

    @foods = Food.all
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.js
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render action: 'show', status: :created, location: @food }
      else
        format.html { render action: 'new' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end


  def categories
    @food = Food.find(params[:id])
    @categories = @food.categories
  end

  def category_add
    @food = Food.find(params[:id])
    @category = Category.find(params[:category])

    if not @food.enrolled_in_category?(@category)
      @food.categories << @category
      flash[:notice] = 'Categoria associada'
    else
      flash[:notice] = 'Categoria já associada'
    end
    redirect_to @food
  end

  def category_remove
    @food = Food.find(params[:id])
    category_ids = params[:categories]

    unless category_ids.blank?
      category_ids.each do |category_id|
        category = Category.find(category_id)
        if @food.enrolled_in_category?(category)
          logger.info "Removendo a categoria"
          @food.categories.delete(category)
          flash[:notice] = 'Categoria removida'
        end
      end
    end
    redirect_to @food
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :description)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for @food, html: {class: "form-horizontal", role: "form"} do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: "form-control" %>
    </div> <!-- end col-sm-9 -->
  </div> <!-- end form-group -->
  <div class="form-group">
    <%= f.label :description, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_area :description, class: "form-control" %>
    </div> <!-- end col-sm-9 -->
  </div> <!-- end form-group -->
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit "Enviar", class: "btn btn-default" %>
    </div> <!-- end col-sm-offset-3 col-sm-9 -->
  </div> <!-- end form-group -->
<% end %> <!-- end form_for -->

app/views/foods/create.js.erb
$('select#food').append('<option value="<%= @food.id %>" selected><%= @food.name %></option>')

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<h1>Listing foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.description %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= action_title "Cadastrar Novo Prato" %>
      </div>
      <div class="panel-body">
        <ul>
          <% @food.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

      </div> <!-- end panel-body -->
    </div> <!-- end panel panel-default -->
  </div> <!-- end col-md-6 -->
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2><small>Pratos Cadastrados</small></h2>
      </div>
      <div class="panel-body">
        <div class="list-group">
          <% @foods.each do |food| %>
            <%= link_to([food], :class => "list-group-item") do %>
              <h4 class="list-group-item-heading">
                <%= food.name %>
              </h4> <!-- end h4 -->
            <% end %> <!-- end link_to -->
          <% end %> <!-- end each -->
        </div> <!-- end list-group -->
      </div> <!-- end panel-body -->
    </div> <!-- end panel panel-default -->
  </div> <!-- end col-md-6 -->
</div> <!-- end row -->

app/views/foods/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="panel panel-default">
  <div class="panel-heading">
    <%= action_title @food.name %>

    <% @food.categories.each do |category| %>
      <span class="label label-default">
        <%= category.name %>
      </span>
    <% end %> <!-- end each -->
    
    <% if @food.unenrolled_categories.count > 0 %>
      <%= form_tag(category_add_food_path(@food), class: "form-inline", role: "form") do %>
        <div class="form-group">
          <%= select_tag(:category, options_from_collection_for_select(@food.unenrolled_categories, :id, :name), :class => 'form-control') %>
        </div>
        <div class="form-group">
          <%= submit_tag "Adicionar", class: "btn btn-default" %>
        </div>
      <% end %>
    <% end %>
  </div> <!-- end panel-heading -->
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">
      </div> <!-- end col-md-2 -->
      <div class="col-md-10">
        <address>
          <strong><%= @food.name %></strong> - <%= link_to "Editar", edit_food_path(@food) %><br>
          <%= @food.description %>
        </address> <!--  end address -->
      </div> <!-- end col-md-10 -->
    </div> <!-- end row -->
  </div> <!-- end panel-body -->
</div> <!-- end panel panel-default -->

<div class="panel panel-default">
  <div class="panel-heading">
    <h2><small>Presente nos seguintes estabelecimentos:</small></h2>
  </div> <!-- end panel-heading -->
  <div class="panel-body">
    <div class="row">
      <div class="col-md-12">
        <div class="list-group">
          <% @food.establishments.each do |establishment| %>
            <%= link_to([establishment], :class => "list-group-item") do %>
              <h4 class="list-group-item-heading">
                <%= establishment.name %>
              </h4>
            <% end %> <!-- end link_to -->
          <% end %> <!-- end each -->
        </div> <!-- end list-group -->
      </div> <!-- end col-md-12 -->
    </div> <!-- end row -->
  </div> <!-- end panel-body -->
</div> <!-- end panel panel-default -->

<%= link_to 'Voltar', establishments_path %>