config/routes.rb
Fourk::Application.routes.draw do
  resources :rates

  resources :prices

  resources :categories

  get '/uso', to: 'welcome#usage'
  get '/privacidade', to: 'welcome#privacy'
  get '/', to: 'welcome#index'
  root :to => 'welcome#index'

  get '/establishments/:id/foods', to: 'establishments#foods'

  resources 'establishments', only: [:index, :new, :create, :show, :edit, :update] do
    member do
      get :foods
      post :food_add
      post :food_remove

      get :categories
      post :category_add
      post :category_remove
    end
  end
  
  resources :foods, only: [:index, :new, :create, :show, :edit, :update] do
    member do
      get :categories
      post :category_add
      post :category_remove
    end
  end

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/price.rb
class Price < ActiveRecord::Base
  validates :value, presence: true

  belongs_to :food
  has_many :rates, as: :rateable
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)

    respond_to do |format|
      if @price.save
        if price_params[:establishment_id]
          @establishment = Establishment.find(price_params[:establishment_id])
          format.html { redirect_to @establishment, notice: 'Price was successfully saved.' }
        else
          format.html { redirect_to @price, notice: 'Price was successfully created.' }
          format.json { render action: 'show', status: :created, location: @price }
        end
      else
        format.html { render action: 'new' }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:value, :food_id, :establishment_id)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= form_for(@price) do |f| %>
  <% if @price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% @price.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :food_id %><br>
    <%= f.number_field :food_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prices/_new_price.html.erb
<div class='new_price'>
  <div class="form_rate">
    <%= form_for Price.new, html: {class: "form-inline", role: "form"} do |f| %>
      <div class="form-group">
        <%= f.label :value, class: "col-sm-3 sr-only" %>
        <div class="col-sm-9">
          Valor: <%= f.text_field :value, class: "form-control" %>
        </div> <!-- end col-sm-9 -->
      </div> <!-- end form-group -->
      <%= f.hidden_field :food_id, :value => food.id %>
      <%= f.hidden_field :establishment_id, :value => establishment.id %>
      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
          <%= f.submit "Cadastrar", class: "btn btn-default" %>
        </div> <!-- end col-sm-offset-3 col-sm-9 -->
      </div> <!-- end form-group -->
    <% end %> <!-- end form_for -->
  </div>
</div>

app/views/prices/edit.html.erb
<h1>Editing price</h1>

<%= render 'form' %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<h1>Listing prices</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Food</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= price.value %></td>
        <td><%= price.food_id %></td>
        <td><%= link_to 'Show', price %></td>
        <td><%= link_to 'Edit', edit_price_path(price) %></td>
        <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price', new_price_path %>

app/views/prices/new.html.erb
<h1>New price</h1>

<%= render 'form' %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @price.value %>
</p>

<p>
  <strong>Food:</strong>
  <%= @price.food_id %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>