config/routes.rb
Fourk::Application.routes.draw do
  resources :rates

  resources :prices

  resources :categories

  get '/uso', to: 'welcome#usage'
  get '/privacidade', to: 'welcome#privacy'
  get '/', to: 'welcome#index'
  root :to => 'welcome#index'

  get '/establishments/:id/foods', to: 'establishments#foods'

  resources 'establishments', only: [:index, :new, :create, :show, :edit, :update] do
    member do
      get :foods
      post :food_add
      post :food_remove

      get :categories
      post :category_add
      post :category_remove
    end
  end
  
  resources :foods, only: [:index, :new, :create, :show, :edit, :update] do
    member do
      get :categories
      post :category_add
      post :category_remove
    end
  end

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/establishment.rb
class Establishment < ActiveRecord::Base
  validates :name, :address, :city, presence: true

  has_and_belongs_to_many :foods
  has_and_belongs_to_many :categories

  # Check if a establishment is enrolled with a food
  def enrolled_in?(food)
    self.foods.include?(food)
  end

  # Return foods that is not enrolled with the establishment
  def unenrolled_foods
    Food.all - self.foods
  end

  def enrolled_in_category?(category)
    self.categories.include?(category)
  end

  def unenrolled_categories
    Category.all - self.categories
  end
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  def index
    @establishments = Establishment.all

    @foods = Food.all
  end

  def new
    @establishment = Establishment.new

    @establishments = Establishment.all
  end

  def create
    @establishment = Establishment.new(params_establishment(params))

    if @establishment.save
      redirect_to @establishment
    else
      @establishments = Establishment.all
      render "new"
    end
  end

  def show
    @establishment = Establishment.find(params[:id])

    @food = Food.new

    @price = Price.new

    @rate = Rate.new
  end

  def edit
    @establishment = Establishment.find(params[:id])
  end

  def update
    @establishment = Establishment.find(params[:id])

    if @establishment.update_attributes!(params_establishment(params))
      redirect_to @establishment
    else
      render "edit"
    end
  end

  # Methods to add and remove foods from establishments
  def foods
    @establishment = Establishment.find(params[:id])
    @foods = @establishment.foods

    respond_to do |format|
      format.json { render 'foods/index' }
    end
  end

  def food_add
    @establishment = Establishment.find(params[:id])
    @food = Food.find(params[:food])

    if not @establishment.enrolled_in?(@food)
      @establishment.foods << @food
      flash[:notice] = 'Comida associada ao restaurante'
    else
      flash[:notice] = 'Comida já associada ao restaurante'
    end
    redirect_to @establishment
  end

  def food_remove
    @establishment = Establishment.find(params[:id])
    food_ids = params[:foods]

    unless food_ids.blank?
      food_ids.each do |food_id|
        food = Food.find(food_id)
        if @establishment.enrolled_in?(food)
          logger.info "Removendo a comida do restaurante"
          @establishment.foods.delete(food)
          flash[:notice] = 'Comida removida do restaurante'
        end
      end
    end
    redirect_to @establishment
  end


  def categories
    @establishment = Establishment.find(params[:id])
    @categories = @establishment.categories
  end

  def category_add
    @establishment = Establishment.find(params[:id])
    @category = Category.find(params[:category])

    if not @establishment.enrolled_in_category?(@category)
      @establishment.categories << @category
      flash[:notice] = 'Categoria associada ao restaurante'
    else
      flash[:notice] = 'Categoria já associada ao restaurante'
    end
    redirect_to @establishment
  end

  def category_remove
    @establishment = Establishment.find(params[:id])
    category_ids = params[:categories]

    unless category_ids.blank?
      category_ids.each do |category_id|
        category = Category.find(category_id)
        if @establishment.enrolled_in_category?(category)
          logger.info "Removendo a categoria do restaurante"
          @establishment.categories.delete(category)
          flash[:notice] = 'Categoria removida do restaurante'
        end
      end
    end
    redirect_to @establishment
  end

  private
  def params_establishment(params)
    params.require(:establishment).permit(:name, 
                                          :description, 
                                          :address, 
                                          :zipcode,
                                          :city,
                                          :state)
  end
end

app/helpers/establishments_helper.rb
module EstablishmentsHelper
end

app/views/establishments/_form.html.erb
<%= form_for @establishment, html: {class: "form-horizontal", role: "form"} do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: "form-control" %>
    </div> <!-- end col-sm-9 -->
  </div> <!-- end form-group -->
  <div class="form-group">
    <%= f.label :description, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_area :description, class: "form-control" %>
    </div> <!-- end col-sm-9 -->
  </div> <!-- end form-group -->
  <div class="form-group">
    <%= f.label :address, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :address, class: "form-control" %>
    </div> <!-- end col-sm-9 -->
  </div> <!-- end form-group -->
  <div class="form-group">
    <%= f.label :zipcode, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :zipcode, class: "form-control" %>
    </div> <!-- end col-sm-9 -->
  </div> <!-- end form-group -->
  <div class="form-group">
    <%= f.label :city, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :city, class: "form-control" %>
    </div> <!-- end col-sm-9 -->
  </div> <!-- end form-group -->
  <div class="form-group">
    <%= f.label :state, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :state, class: "form-control" %>
    </div> <!-- end col-sm-9 -->
  </div> <!-- end form-group -->
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit "Enviar", class: "btn btn-default" %>
    </div> <!-- end col-sm-offset-3 col-sm-9 -->
  </div> <!-- end form-group -->
<% end %> <!-- end form_for -->

app/views/establishments/edit.html.erb
<%= render 'form' %>

<%= link_to "Cancelar", @establishment %>

app/views/establishments/index.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= action_title "Estabelecimentos" %>
        <%= link_to "Novo estabelecimento", new_establishment_path, class: "btn btn-default" %>
      </div>
      <div class="panel-body">
        <div class="list-group">
          <% @establishments.each do |establishment| %>
            <%= link_to([establishment], :class => "list-group-item") do %>
              <h4 class="list-group-item-heading">
                <%= establishment.name %>
              </h4>

              <% establishment.categories.each do |category| %>
                <span class="label label-default">
                  <%= category.name %>
                </span>
              <% end %> <!-- end each -->
            <% end %> <!-- end link_to -->
          <% end %> <!-- end each -->
        </div> <!-- end list-group -->
      </div> <!-- end panel-body -->
    </div> <!-- end panel panel-default -->
  </div> <!-- end col-md-6 -->
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2><small>Pratos</small></h2>
        <%= link_to "Novo prato", new_food_path, class: "btn btn-default" %>
      </div>
      <div class="panel-body">
        <div class="list-group">
          <% @foods.each do |food| %>
            <%= link_to([food], :class => "list-group-item") do %>
              <h4 class="list-group-item-heading">
                <%= food.name %>
              </h4>

              <% food.categories.each do |category| %>
                <span class="label label-default">
                  <%= category.name %>
                </span>
              <% end %> <!-- end each -->
            <% end %> <!-- end link_to -->
          <% end %> <!-- end each -->
        </div> <!-- end list-group -->
      </div> <!-- end panel-body -->
    </div> <!-- end panel panel-default -->
  </div> <!-- end col-md-6 -->
</div> <!-- end row -->

app/views/establishments/new.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= action_title "Cadastrar Novo Estabelecimento" %>
      </div>
      <div class="panel-body">
        <ul>
          <% @establishment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>

        <%= render 'form' %>

        <%= link_to "Cancelar", establishments_path %>
      </div> <!-- end panel-body -->
    </div> <!-- end panel panel-default -->
  </div> <!-- end col-md-6 -->
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2><small>Estabelecimentos Cadastrados</small></h2>
      </div>
      <div class="panel-body">
        <div class="list-group">
          <% @establishments.each do |establishment| %>
            <%= link_to([establishment], :class => "list-group-item") do %>
              <h4 class="list-group-item-heading">
                <%= establishment.name %>
              </h4> <!-- end h4 -->
            <% end %> <!-- end link_to -->
          <% end %> <!-- end each -->
        </div> <!-- end list-group -->
      </div> <!-- end panel-body -->
    </div> <!-- end panel panel-default -->
  </div> <!-- end col-md-6 -->
</div> <!-- end row -->

app/views/establishments/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <!-- Helper "action_title" - Establishment Name -->
    <%= action_title @establishment.name %>

    <!-- Ẽstablishment Categories -->
    <% @establishment.categories.each do |category| %>
      <span class="label label-default">
        <%= category.name %>
      </span>
    <% end %> <!-- end each -->
    
    <% if @establishment.unenrolled_categories.count > 0 %>
      <%= form_tag(category_add_establishment_path(@establishment), class: "form-inline", role: "form") do %>
        <div class="form-group">
          <%= select_tag(:category, options_from_collection_for_select(@establishment.unenrolled_categories, :id, :name), :class => 'form-control') %>
        </div>
        <div class="form-group">
          <%= submit_tag "Adicionar", class: "btn btn-default" %>
        </div>
      <% end %> <!-- end form_tag -->
    <% end %> <!-- end if -->
  </div> <!-- end panel-heading -->

  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">
      </div> <!-- end col-md-2 -->
      <div class="col-md-5">
        <address>
          <!-- Establishment Informations -->
          <strong><%= @establishment.name %></strong> - <%= link_to "Editar", edit_establishment_path(@establishment) %><br>
          Descrição: <%= @establishment.description %><br>
          Endereço: <%= @establishment.address %><br>
          CEP: <%= @establishment.zipcode %><br>
          Cidade: <%= @establishment.city %><br>
          Estado: <%= @establishment.state %>
        </address> <!--  end address -->
      </div> <!-- end col-md-10 -->

      <div class="col-md-5">
        <!-- Establishment General Rate -->
        Nota Geral: 
        <% general_rate = 0 %>
        <% general_rate_count = 0 %>

        <% for food in @establishment.foods %>
          <% food_rate_average = food.rates.where(establishment_id: @establishment).average(:value) %>
          <% food_rate_count = 1 %>

          <% if food_rate_average == nil %>
            <% food_rate_average = 0 %>
            <% food_rate_count = 0 %>
          <% end %> <!-- end if -->

          <% general_rate += food_rate_average %>
          <% general_rate_count += food_rate_count %>
        <% end %> <!-- end for -->

        <% if general_rate > 0 %>
          <% general_rate = general_rate / general_rate_count %>
          <%= sprintf('%.1f', general_rate) %>
        <% else %>
          Não avaliado
        <% end %> <!-- end if -->
      </div> <!-- end col-md-5 -->
    </div> <!-- end row -->
  </div> <!-- end panel-body -->
</div> <!-- end panel panel-default -->

<div class="panel panel-default">
  <div class="panel-heading">
    <h2><small>Serviços:</small></h2>
  </div> <!-- end panel-heading -->
  <div class="panel-body">
    <div class="row">
      <div class="col-md-12">
        <div class="list-group">
          <% @establishment.foods.each do |food| %>
            <div class="list-group-item">
              <!-- Establishment Single Food -->
              <%= link_to([food]) do %>
                <h4 class="list-group-item-heading">
                  <%= food.name %>
                </h4>
              <% end %> <!-- end link_to -->

              <span class="label label-default">
                <!-- Food's Price -->
                <% if food.prices.where(establishment_id: @establishment).count > 0 %>
                  R$ <%= sprintf('%.2f', food.prices.where(establishment_id: @establishment).last.value) %>
                <% else %>
                  Sem preço definido
                <% end %> <!-- end if -->
              </span>

              <span class="label label-default">
                <!-- Food's Rate -->
                <% if food.rates.where(establishment_id: @establishment).count > 0 %>
                  Nota: <%= sprintf('%.1f',   food.rates.where(establishment_id: @establishment).average(:value)) %>
                <% else %>
                  Nota: Não avaliado
                <% end %> <!-- end if -->
              </span>

              <!-- Add New Price -->
              <button class="btn btn-default btn-price">Novo preço</button>
              <div id="popover-head-price" class="hide">Novo preço:</div>
              <div id="popover-content-price" class="hide">
                <%= new_price(food, @establishment) %>
              </div>

              <!-- New Rate -->
              <button class="btn btn-default btn-rate">Avaliar prato</button>
              <div id="popover-head-rate" class="hide">Dê uma nota:</div>
              <div id="popover-content-rate" class="hide">
                <%= new_rate(food, @establishment) %>
              </div>

              <!-- JavaScript - Popover -->
              <script type="text/javascript">
                $('.btn-price').popover({
                  html: true,
                  title: function() {
                    return $('#popover-head-price').html();
                  },
                  content: function() {
                    return $('#popover-content-price').html();
                  }
                });

                $('.btn-rate').popover({
                  html: true,
                  title: function() {
                    return $('#popover-head-rate').html();
                  },
                  content: function() {
                    return $('#popover-content-rate').html();
                  }
                });
              </script> <!-- end script -->

            </div> <!-- end list-group-item -->
          <% end %> <!-- end each -->
        </div> <!-- end list-group -->
      </div> <!-- end col-md-12 -->

      <% if @establishment.unenrolled_foods.count > 0 %>
        <div class="col-md-6">
          <!-- Enroll Food to Establishment -->
          <p>Adicione um prato aqui:</p>
          <%= form_tag(food_add_establishment_path(@establishment), class: "form-inline", role: "form") do %>
            <div class="form-group">
              <%= select_tag(:food, options_from_collection_for_select(@establishment.unenrolled_foods, :id, :name), :class => 'form-control') %>
            </div>
            <div class="form-group">
              <%= submit_tag "Adicionar", class: "btn btn-default" %>
            </div>
          <% end %> <!-- end form_tag -->
        </div> <!-- end col-md-6 -->
      <% end %> <!-- end if -->

      <div class="col-md-6">
        <!-- Register New Food -->
        <p>Cadastre um novo prato:</p>
        <%= form_for @food, html: {class: "form-inline", role: "form"}, remote: true do |f| %>
          <div class="form-group">
            <%= f.label :name, class: "col-sm-3 sr-only" %>
            <div class="col-sm-9">
              <%= f.text_field :name, class: "form-control" %>
            </div> <!-- end col-sm-9 -->
          </div> <!-- end form-group -->
          <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
              <%= f.submit "Cadastrar", class: "btn btn-default" %>
            </div> <!-- end col-sm-offset-3 col-sm-9 -->
          </div> <!-- end form-group -->
        <% end %> <!-- end form_for -->
      </div> <!-- end col-md-6 -->
    </div> <!-- end row -->
  </div> <!-- end panel-body -->
</div> <!-- end panel panel-default -->

<p><%= link_to "Voltar", establishments_path %></p>